name: CI/CD Pipeline - DevOps Static Site

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: devopsacr206
  IMAGE_NAME: devops-static-site
  RESOURCE_GROUP: devops-rg
  AKS_CLUSTER: devops-aks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Tag Docker image for ACR
        run: docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to ACR
        run: docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }} --overwrite-existing

      - name: Redeploy to AKS
        run: |
          kubectl set image deployment/devops-static-site devops-static-site=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest --record
          kubectl rollout status deployment/devops-static-site
